const CATALOG = [
{"id": "lente-minimal", "category": "Pendant Lights", "title": "Lente Minimal Pendant", "description": "Soft silhouette, warm ambient glow.", "price": "$189", "image": "assets/products/lente-minimal.svg", "remote": "https://www.schoener-wohnen-kollektion.de/media/96/b3/a5/1751885384/SCHOENER-WOHNEN-Pendelleuchte%20Lente-wei%C3%9F-14606-16.jpg"},
{"id": "china-led-floor", "category": "Floor Lamps", "title": "China LED Floor Lamp", "description": "Slim floor lighting for reading corners.", "price": "$249", "image": "assets/products/china-led-floor.svg", "remote": "https://www.loftmodern.com/cdn/shop/files/ChinaLEDFloor-Black_1e128d4d-4563-4106-8ed4-7278450897de.jpg?v=1707073544"},
{"id": "crown-dome", "category": "Table Lamps", "title": "Crown Dome Table Lamp", "description": "Compact task light with sculptural form.", "price": "$139", "image": "assets/products/crown-dome.svg", "remote": "https://www.dusklights.co.uk/cdn/shop/files/6898WHD1.jpg?v=1774966207&width=1200"},
{"id": "selene-tier", "category": "Chandeliers", "title": "Selene Two-Tier Chandelier", "description": "Statement centerpiece with layered glass.", "price": "$899", "image": "assets/products/selene-tier.svg", "remote": "https://assets.wfcdn.com/im/80832826/compr-r85/2701/270151749/Selene%2B48%22%2B18-Light%2BModern%2BTwo-Tier%2BChandelier%2Bw/%2BSwirled%2BGlass.jpg"},
{"id": "viegas-wall", "category": "Wall Lights", "title": "Viegas LED Wall Light", "description": "Architectural wall wash for modern rooms.", "price": "$179", "image": "assets/products/viegas-wall.svg", "remote": "https://onlinelighting.com.au/images/detailed/143/Eglo-Viegas-95422.jpg"},
{"id": "slim-round-led", "category": "LED Lighting", "title": "Slim Round LED Ceiling Light", "description": "Low-profile illumination for everyday spaces.", "price": "$119", "image": "assets/products/slim-round-led.svg", "remote": "https://www.optonicaled.com/uploads/live/product_images/style_compressed/2903_1708617431.png"},
{"id": "essential-smart", "category": "Smart Lighting", "title": "Essential Smart Bulb", "description": "App-ready lighting for routines and scenes.", "price": "$29", "image": "assets/products/essential-smart.svg", "remote": "https://www.istorm.gr/cdn/shop/files/929002468801_01.jpg?v=1720449920"},
{"id": "focus-outdoor", "category": "Outdoor", "title": "Focus Outdoor Wall Sconce", "description": "Weather-ready accent lighting for entrances.", "price": "$159", "image": "assets/products/focus-outdoor.svg", "remote": "https://lutec-lighting.com/cdn/shop/products/2_3b68e7ba-c880-4047-af96-48f5f36e0e4b.jpg?v=1646820718&width=1946"},
{"id": "sabinar-mini", "category": "Pendant Lights", "title": "Sabinar Mini Pendant", "description": "Small-scale pendant for kitchens and bars.", "price": "$129", "image": "assets/products/sabinar-mini.svg", "remote": "https://onlinelighting.com.au/images/detailed/204/96981.jpg"},
{"id": "black-45", "category": "Chandeliers", "title": "45-Light Black Chandelier", "description": "Graphic statement lighting for tall spaces.", "price": "$1,249", "image": "assets/products/black-45.svg", "remote": "https://www.wegotlites.com/assets/images/771/771606-01.jpg"},
{"id": "eastyn-starburst", "category": "Chandeliers", "title": "Eastyn Starburst Chandelier", "description": "Layered starburst form with refined finish.", "price": "$1,095", "image": "assets/products/eastyn-starburst.svg", "remote": "https://www.visualcomfort.com/media/catalog/product/c/c/cc16612bbs_2.png"},
{"id": "elite-globe", "category": "Chandeliers", "title": "Elite Globe Chandelier", "description": "Spherical glass composition for dining rooms.", "price": "$1,099", "image": "assets/products/elite-globe.svg", "remote": "https://luxuryliving.nl/cdn/shop/products/Joy-30_2.jpg?v=1677004827"}
];
window.LUMENZA = window.LUMENZA || {}; window.LUMENZA.catalog = CATALOG;
