const CATALOG = [
{"id": "lente-minimal", "category": "Pendant Lights", "title": "Lente Minimal Pendant", "description": "Soft silhouette, warm ambient glow.", "price": "$189", "image": "https://ledarena.pl/hpeciai/60b22bdbe5fc5bd27df52ae16dd65885/pol_pl_Lampa-wiszaca-bezowa-zlota-E27-nad-stol-NOWOCZESNA-1133_17.jpg"},
{"id": "china-led-floor", "category": "Floor Lamps", "title": "China LED Floor Lamp", "description": "Slim floor lighting for reading corners.", "price": "$249", "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/8475bfb0-4ad2-4b8e-9a13-c102a580bcc7.jpg"},
{"id": "crown-dome", "category": "Table Lamps", "title": "Crown Dome Table Lamp", "description": "Compact task light with sculptural form.", "price": "$139", "image": "https://vakkerlight.com/cdn/shop/files/Hanna_Table_Lamp__122.jpg?v=1695432663&width=1600"},
{"id": "selene-tier", "category": "Chandeliers", "title": "Selene Two-Tier Chandelier", "description": "Statement centerpiece with layered glass.", "price": "$899", "image": "https://favourite-light.com/docs/folder/smb/Photo1500x1500/webp/4503-30P/4503-30P.webp"},
{"id": "viegas-wall", "category": "Wall Lights", "title": "Viegas LED Wall Light", "description": "Architectural wall wash for modern rooms.", "price": "$179", "image": "https://onlinelighting.com.au/images/detailed/143/Eglo-Viegas-95422.jpg"},
{"id": "slim-round-led", "category": "LED Lighting", "title": "Slim Round LED Ceiling Light", "description": "Low-profile illumination for everyday spaces.", "price": "$119", "image": "https://lightingnewyork.com/dw/image/v2/BHCF_PRD/on/demandware.static/-/Sites-master-catalog-lny/default/dwe2c38565/brand/mtl/productimages/m10802wh_800x800.jpg?sfrm=jpg&sh=800&sm=fit&sw=800"},
{"id": "essential-smart", "category": "Smart Lighting", "title": "Essential Smart Bulb", "description": "App-ready lighting for routines and scenes.", "price": "$29", "image": "https://homegard.fr/cdn/shop/files/Francais_Francais_20.jpg?v=1759721299"},
{"id": "focus-outdoor", "category": "Outdoor", "title": "Focus Outdoor Wall Sconce", "description": "Weather-ready accent lighting for entrances.", "price": "$159", "image": "https://www.simes.it/asset/images/versioni/big/icon_h950_14_led_09.jpg"},
{"id": "sabinar-mini", "category": "Pendant Lights", "title": "Sabinar Mini Pendant", "description": "Small-scale pendant for kitchens and bars.", "price": "$129", "image": "https://cdn.shopify.com/s/files/1/0012/2005/1002/files/BlackSmall.jpg?v=1747649256"},
{"id": "black-45", "category": "Chandeliers", "title": "45-Light Black Chandelier", "description": "Graphic statement lighting for tall spaces.", "price": "$1,249", "image": "https://cdn.tanguay.ca/images/products/1920px/0828974.jpg"},
{"id": "eastyn-starburst", "category": "Chandeliers", "title": "Eastyn Starburst Chandelier", "description": "Layered starburst form with refined finish.", "price": "$1,095", "image": "https://maisonroseaux.com/cdn/shop/files/R39LHT0048-BLK-M_01.jpg?v=1707291316&width=1920"},
{"id": "elite-globe", "category": "Chandeliers", "title": "Elite Globe Chandelier", "description": "Spherical glass composition for dining rooms.", "price": "$1,099", "image": "https://www.duttonbrown.com/cdn/shop/files/12-crown-chandelier-32-nickel-barely.jpg?v=1747968635&width=2048"}
];
window.LUMENZA=window.LUMENZA||{};window.LUMENZA.catalog=CATALOG;