const products=[
{id:1,name:'Lente Minimal Pendant',cat:'Pendants',price:189,img:'https://www.schoener-wohnen-kollektion.de/media/96/b3/a5/1751885384/SCHOENER-WOHNEN-Pendelleuchte%20Lente-wei%C3%9F-14606-16.jpg',desc:'Slim contemporary pendant for dining and kitchen spaces.'},
{id:2,name:'China LED Floor Lamp',cat:'Floor Lamps',price:279,img:'https://www.loftmodern.com/cdn/shop/files/ChinaLEDFloor-Black_1e128d4d-4563-4106-8ed4-7278450897de.jpg?v=1707073544',desc:'Minimal black floor lamp with warm integrated LED light.'},
{id:3,name:'Crown Dome Table Lamp',cat:'Table Lamps',price:149,img:'https://www.dusklights.co.uk/cdn/shop/files/6898WHD1.jpg?v=1774966207&width=1200',desc:'Soft dome silhouette for desks, consoles and bedside tables.'},
{id:4,name:'Selene Two-Tier Chandelier',cat:'Chandeliers',price:1299,img:'https://assets.wfcdn.com/im/80832826/compr-r85/2701/270151749/Selene%2B48%22%2B18-Light%2BModern%2BTwo-Tier%2BChandelier%2Bw/%2BSwirled%2BGlass.jpg',desc:'A sculptural gold fixture with diffused glass globes.'},
{id:5,name:'Viegas LED Wall Light',cat:'Wall Lights',price:119,img:'https://onlinelighting.com.au/images/detailed/143/Eglo-Viegas-95422.jpg',desc:'Vertical brushed-metal wall fixture with soft up and down light.'},
{id:6,name:'Slim Round LED Ceiling Light',cat:'LED',price:89,img:'https://www.optonicaled.com/uploads/live/product_images/style_compressed/2903_1708617431.png',desc:'Low-profile ceiling light for clean, even illumination.'},
{id:7,name:'Essential Smart Bulb',cat:'Smart',price:39,img:'https://www.istorm.gr/cdn/shop/files/929002468801_01.jpg?v=1720449920',desc:'Connected bulb for adjustable scenes and everyday smart control.'},
{id:8,name:'Focus Outdoor Wall Sconce',cat:'Outdoor',price:129,img:'https://lutec-lighting.com/cdn/shop/products/2_3b68e7ba-c880-4047-af96-48f5f36e0e4b.jpg?v=1646820718&width=1946',desc:'Dark architectural sconce for entrances, patios and exterior walls.'},
{id:9,name:'Sabinar Mini Pendant',cat:'Pendants',price:109,img:'https://onlinelighting.com.au/images/detailed/204/96981.jpg',desc:'Compact white pendant with a warm natural-wood accent.'},
{id:10,name:'45-Light Black Chandelier',cat:'Chandeliers',price:921,img:'https://www.wegotlites.com/assets/images/771/771606-01.jpg',desc:'Bold black chandelier with soft globe illumination for larger rooms.'},
{id:11,name:'Eastyn Starburst Chandelier',cat:'Chandeliers',price:899,img:'https://www.visualcomfort.com/media/catalog/product/c/c/cc16612bbs_2.png',desc:'Burnished-brass starburst fixture for dining and statement spaces.'},
{id:12,name:'Elite Globe Chandelier',cat:'Chandeliers',price:799,img:'https://luxuryliving.nl/cdn/shop/products/Joy-30_2.jpg?v=1677004827',desc:'Modern ring chandelier with soft globe illumination.'}
];
let cart=JSON.parse(localStorage.getItem('lumenza-cart')||'[]');let wishes=JSON.parse(localStorage.getItem('lumenza-wish')||'[]');let activeCat='All';
const $=s=>document.querySelector(s);const grid=$('#productGrid');
function money(n){return '$'+n.toLocaleString('en-US',{minimumFractionDigits:2})}
function render(){let list=products.filter(p=>activeCat==='All'||p.cat===activeCat);const q=$('#searchInput').value.trim().toLowerCase();if(q)list=list.filter(p=>(p.name+' '+p.cat+' '+p.desc).toLowerCase().includes(q));const sort=$('#sort').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);grid.innerHTML=list.map(p=>`<article class="product"><div class="product-image"><img src="${p.img}" alt="${p.name}" loading="lazy" onerror="this.closest('.product-image').classList.add('broken');this.style.display='none'"><button class="heart" data-wish="${p.id}">${wishes.includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><span class="product-cat">${p.cat.toUpperCase()}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><span class="price">${money(p.price)}</span><button class="add" data-add="${p.id}">Add to cart</button></div></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(+b.dataset.wish));updateCounts()}
function add(id){cart.push(id);save();toast('Added to cart');openCart()}
function toggleWish(id){wishes=wishes.includes(id)?wishes.filter(x=>x!==id):[...wishes,id];save();render();toast(wishes.includes(id)?'Saved to wishlist':'Removed from wishlist')}
function save(){localStorage.setItem('lumenza-cart',JSON.stringify(cart));localStorage.setItem('lumenza-wish',JSON.stringify(wishes));updateCounts()}
function updateCounts(){$('#cartCount').textContent=cart.length;$('#wishCount').textContent=wishes.length}
function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show');renderCart()}function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show')}
function renderCart(){const el=$('#cartItems');if(!cart.length){el.innerHTML='<p style="color:#766f68">Your cart is empty. Explore the collection and add something beautiful.</p>';$('#cartTotal').textContent='$0.00';return}const counts={};cart.forEach(id=>counts[id]=(counts[id]||0)+1);let total=0;el.innerHTML=Object.entries(counts).map(([id,qty])=>{const p=products.find(x=>x.id==id);total+=p.price*qty;return `<div class="drawer-item"><img src="${p.img}" alt="${p.name}"><div><h4>${p.name}</h4><small>${qty} × ${money(p.price)}</small></div><button class="remove" data-remove="${p.id}">Remove</button></div>`}).join('');$('#cartTotal').textContent=money(total);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const i=cart.indexOf(+b.dataset.remove);if(i>-1)cart.splice(i,1);save();renderCart();render()})}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
$('#searchForm').onsubmit=e=>{e.preventDefault();render();$('#products').scrollIntoView({behavior:'smooth'})};$('#searchInput').oninput=render;$('#sort').onchange=render;$('#clearFilter').onclick=()=>{activeCat='All';render()};document.querySelectorAll('[data-cat]').forEach(a=>a.onclick=()=>{activeCat=a.dataset.cat;render()});$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;$('#wishlistBtn').onclick=()=>{activeCat='All';$('#searchInput').value='';render();toast(wishes.length?`${wishes.length} saved item${wishes.length>1?'s':''}`:'Your wishlist is empty')};$('#checkout').onclick=()=>toast('Demo checkout — support can help with orders.');$('#findBtn').onclick=()=>{const space=$('#space').value,mood=$('#mood').value;const map={'Living room':['Floor Lamps','Table Lamps','Chandeliers'],'Bedroom':['Table Lamps','Wall Lights','Smart'],'Kitchen':['Pendants','LED','Smart'],'Office':['Table Lamps','LED','Smart'],'Outdoor':['Outdoor','Wall Lights']};const picks=map[space].join(', ');$('#finderResult').textContent=`For a ${mood.toLowerCase()} ${space.toLowerCase()}, start with ${picks}.`;};$('#supportForm').onsubmit=e=>{e.preventDefault();$('#supportMsg').textContent='Thanks — your message is ready for the LUMENZA support team.';e.target.reset()};render();
